/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learning;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vincent
 */
public class MyNewGui extends javax.swing.JFrame {

	static class Question {

		Image flag;
		String answer;

		public Question(Image img, String ans) {
			flag = img;
			answer = ans;
		}

	}
	private final Question[] questions;
	private Question currentQuestion;

	boolean YouCanExitNow = false;
	boolean YouCanExitNow2 = false;
	String MyPass1;
	String MyPass2;
	String MyHint;

	/**
	 * Creates new form MyNewGui
	 */
	public MyNewGui() throws IOException, InterruptedException {
		initComponents();
		questions = new Question[]{
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/JamaicanFlag.png")), "jamaica"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Mexican Flag.png")), "mexico"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Netherland Flag.png")), "netherlands"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Russian Fla.png")), "russia"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Irish Flag.png")), "ireland"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Rwanda Flag.png")), "rwanda"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Pakistan Flag.png")), "pakistan"),
			new Question(ImageIO.read(getClass().getClassLoader().getResource("images/Tommy.png")), "tommy")
		};

		currentQuestion = questions[getRandomQuestion()];
		drawFlag(currentQuestion);
	}

	private int getRandomQuestion() {
		return (int) (Math.random() * questions.length);
	}
	
	private void drawFlag(Question question) {
		BufferedImage resizedImage = new BufferedImage(200, 100, BufferedImage.TYPE_INT_RGB);
		Graphics graf = resizedImage.getGraphics();
		graf.drawImage(question.flag, 0, 0, 200, 100, null);
		flag.setIcon(new ImageIcon(resizedImage));
		
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenTwo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        flag = new javax.swing.JLabel();
        CountryName1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        loginScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        PasswordSetup = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ThisIsMyPassword1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        ThisIsMyPassword2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ThisIsMyHint = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setText("What flag is this?");

        jButton2.setText("Enter Answer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CountryName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryName1ActionPerformed(evt);
            }
        });

        jLabel8.setText("(Enter the name of the country)");

        javax.swing.GroupLayout screenTwoLayout = new javax.swing.GroupLayout(screenTwo);
        screenTwo.setLayout(screenTwoLayout);
        screenTwoLayout.setHorizontalGroup(
            screenTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenTwoLayout.createSequentialGroup()
                .addGroup(screenTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screenTwoLayout.createSequentialGroup()
                        .addGroup(screenTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CountryName1))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8))
                    .addGroup(screenTwoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(flag, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        screenTwoLayout.setVerticalGroup(
            screenTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenTwoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(flag, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(screenTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel1.setText("Enter your password:");

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel7.setText("Login");

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 166, Short.MAX_VALUE))
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(23, 23, 23)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel3.setText("Password Setup");

        jLabel4.setText("Enter your new password: ");

        ThisIsMyPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThisIsMyPassword1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Re-enter your new password: ");

        ThisIsMyPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThisIsMyPassword2ActionPerformed(evt);
            }
        });

        jButton1.setText("Next >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter a password hint: ");

        javax.swing.GroupLayout PasswordSetupLayout = new javax.swing.GroupLayout(PasswordSetup);
        PasswordSetup.setLayout(PasswordSetupLayout);
        PasswordSetupLayout.setHorizontalGroup(
            PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordSetupLayout.createSequentialGroup()
                .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(PasswordSetupLayout.createSequentialGroup()
                            .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(35, 35, 35)
                            .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ThisIsMyPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ThisIsMyPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ThisIsMyHint, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasswordSetupLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        PasswordSetupLayout.setVerticalGroup(
            PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordSetupLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ThisIsMyPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ThisIsMyPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(PasswordSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ThisIsMyHint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(PasswordSetup, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
		String Typed = new String(Password.getPassword());
		if (Typed.equals(MyPass1)) {
			remove(loginScreen);
			add(screenTwo, BorderLayout.CENTER);
			validate();
			repaint();
		} else {
			JOptionPane.showMessageDialog(this, "Wrong password; hint: " + MyHint, "Password warning", JOptionPane.WARNING_MESSAGE);
		}
    }//GEN-LAST:event_PasswordActionPerformed

    private void ThisIsMyPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThisIsMyPassword1ActionPerformed

    }//GEN-LAST:event_ThisIsMyPassword1ActionPerformed

    private void ThisIsMyPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThisIsMyPassword2ActionPerformed

    }//GEN-LAST:event_ThisIsMyPassword2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		MyPass1 = new String(ThisIsMyPassword1.getPassword());
		MyPass2 = new String(ThisIsMyPassword2.getPassword());
		MyHint = new String(ThisIsMyHint.getText());
		if (MyPass1.equals(MyPass2) && !MyHint.equals("")) {
			remove(PasswordSetup);
			add(loginScreen);
			validate();
			repaint();
		} else {
			if (MyHint.equals("")) {
				JOptionPane.showMessageDialog(this, "You have no password hint", "Password hint warning", JOptionPane.WARNING_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this, "The passwords do not match", "Password match warning", JOptionPane.WARNING_MESSAGE);
			}
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		CheckAnswer();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CountryName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryName1ActionPerformed
        CheckAnswer();
    }//GEN-LAST:event_CountryName1ActionPerformed

	private void CheckAnswer () {
		String CAnswer = new String(CountryName1.getText());
		if (!CAnswer.equals("")) {
			if (CAnswer.toLowerCase().equals(currentQuestion.answer)) {
				JOptionPane.showMessageDialog(this, "Good answer!", "Result", JOptionPane.WARNING_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this, "Wrong answer", "Result", JOptionPane.WARNING_MESSAGE);
			}
			currentQuestion = questions[getRandomQuestion()];
			drawFlag(currentQuestion);
			CountryName1.setText("");
		} else {
			JOptionPane.showMessageDialog(this, "You did not write anything.", "Empty answer warning", JOptionPane.WARNING_MESSAGE);
		}
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MyNewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MyNewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MyNewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MyNewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				try {
					new MyNewGui().setVisible(true);
				} catch (IOException ex) {
					Logger.getLogger(MyNewGui.class.getName()).log(Level.SEVERE, null, ex);
				} catch (InterruptedException ex) {
					Logger.getLogger(MyNewGui.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CountryName1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPanel PasswordSetup;
    private javax.swing.JTextField ThisIsMyHint;
    private javax.swing.JPasswordField ThisIsMyPassword1;
    private javax.swing.JPasswordField ThisIsMyPassword2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel flag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JPanel screenTwo;
    // End of variables declaration//GEN-END:variables
}
